---
blank_issues_enabled: false
contact_links:
  - name: Expensive Tracker AI Community Support
    url: https://github.com/dthoang6/expensive-tracker-ai/discussions
    about: Please ask and answer questions here.
